### PR TITLE
Adds a strictSSL option

### PR DESCRIPTION
**Pull request by k33k00**
by default it is set to true in send_heartbeat as that is the recommended practice from a security point of view. Also it is True by default within the requests package.

It is configurable within the wakatime.cfg

### CODE REVIEW

**Comment by k33k00** [comment]
well something clearly has gone wrong. As it's failing that travis thing. Though I can say it's working for me. 

If you can see what's wrong please let me know. I'm genuinely curious

**Comment by k33k00** [comment]
Looks like it was a problem with if there was no value in the config. Changed it default to true. Also you want to rename the variables like you did with the atom plugin.

**Comment by alanhamlett** [comment]
I'll do this in a separate PR with the config rename, and all these changes included.

**Comment by k33k00** [comment]
okay, no worries. Look forward to the update

**Comment by alanhamlett** [comment]
Fixed with #90.

**Pull request closed without merging**
